const express=require('express');const fs=require('fs');const path=require('path');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const multer=require('multer');
const app=express();const PORT=process.env.PORT||3000;const SECRET=process.env.JWT_SECRET||'local-demo-secret-change-before-deploy';
const ROOT=__dirname,DATA=path.join(ROOT,'data'),DB=path.join(DATA,'db.json'),UPLOADS=path.join(ROOT,'uploads');
fs.mkdirSync(DATA,{recursive:true});fs.mkdirSync(UPLOADS,{recursive:true});
if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify({users:[],applications:[],messages:[]},null,2));
const read=()=>JSON.parse(fs.readFileSync(DB,'utf8'));const write=d=>fs.writeFileSync(DB,JSON.stringify(d,null,2));
function token(user){return jwt.sign({id:user.id,email:user.email,role:user.role},SECRET,{expiresIn:'7d'})}function auth(req,res,next){try{const t=(req.headers.authorization||'').replace('Bearer ','');req.user=jwt.verify(t,SECRET);next()}catch(e){res.status(401).json({error:'Nicht angemeldet'})}}
function admin(req,res,next){auth(req,res,()=>req.user.role==='admin'?next():res.status(403).json({error:'Admin-Zugriff erforderlich'}))}
const storage=multer.diskStorage({destination:(r,f,cb)=>cb(null,UPLOADS),filename:(r,f,cb)=>cb(null,Date.now()+'-'+f.originalname.replace(/[^a-zA-Z0-9._-]/g,'_'))});const upload=multer({storage,limits:{fileSize:10*1024*1024}});
app.use(express.json({limit:'2mb'}));app.use(express.static(path.join(ROOT,'public')));
app.post('/api/register',async(req,res)=>{const {firstName,lastName,email,password}=req.body;if(!firstName||!lastName||!email||!password||password.length<8)return res.status(400).json({error:'Bitte alle Felder ausfüllen. Passwort mindestens 8 Zeichen.'});const d=read();if(d.users.some(u=>u.email.toLowerCase()===email.toLowerCase()))return res.status(409).json({error:'E-Mail bereits registriert'});const u={id:'U-'+Date.now(),firstName,lastName,email:email.toLowerCase(),password:await bcrypt.hash(password,10),role:'user',createdAt:new Date().toISOString()};d.users.push(u);write(d);res.json({token:token(u),user:{id:u.id,firstName,lastName,email:u.email,role:u.role}})});
app.post('/api/login',async(req,res)=>{const {email,password}=req.body;const adminEmail=process.env.ADMIN_EMAIL,adminPass=process.env.ADMIN_PASSWORD;if(adminEmail&&adminPass&&email===adminEmail&&password===adminPass){const u={id:'ADMIN',email:adminEmail,role:'admin',firstName:'Portal',lastName:'Admin'};return res.json({token:token(u),user:u})}const d=read(),u=d.users.find(x=>x.email===String(email||'').toLowerCase());if(!u||!(await bcrypt.compare(password||'',u.password)))return res.status(401).json({error:'E-Mail oder Passwort falsch'});res.json({token:token(u),user:{id:u.id,firstName:u.firstName,lastName:u.lastName,email:u.email,role:u.role}})});
app.get('/api/me',auth,(req,res)=>{const d=read();if(req.user.role==='admin')return res.json({user:req.user});const u=d.users.find(x=>x.id===req.user.id);res.json({user:{id:u.id,firstName:u.firstName,lastName:u.lastName,email:u.email,role:u.role}})});
app.post('/api/applications',auth,(req,res)=>{const {type,travelPurpose,arrivalDate,departureDate,notes}=req.body;if(!type)return res.status(400).json({error:'Antragstyp fehlt'});const d=read();const a={id:'DE-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-8),userId:req.user.id,type,travelPurpose,arrivalDate,departureDate,notes,status:'Eingegangen',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),documents:[],timeline:[{status:'Eingegangen',date:new Date().toISOString(),note:'Antrag wurde digital eingereicht.'}]};d.applications.push(a);write(d);res.json(a)});
app.get('/api/applications',auth,(req,res)=>{const d=read();res.json(req.user.role==='admin'?d.applications:d.applications.filter(a=>a.userId===req.user.id))});
app.get('/api/applications/:id',auth,(req,res)=>{const a=read().applications.find(x=>x.id===req.params.id);if(!a|| (req.user.role!=='admin'&&a.userId!==req.user.id))return res.status(404).json({error:'Nicht gefunden'});res.json(a)});
app.post('/api/applications/:id/documents',auth,upload.single('document'),(req,res)=>{const d=read(),a=d.applications.find(x=>x.id===req.params.id);if(!a|| (req.user.role!=='admin'&&a.userId!==req.user.id))return res.status(404).json({error:'Nicht gefunden'});if(!req.file)return res.status(400).json({error:'Keine Datei'});a.documents.push({name:req.file.originalname,filename:req.file.filename,size:req.file.size,uploadedAt:new Date().toISOString()});a.updatedAt=new Date().toISOString();write(d);res.json(a)});
app.get('/api/admin/applications',admin,(req,res)=>res.json(read().applications));
app.patch('/api/admin/applications/:id',admin,(req,res)=>{const d=read(),a=d.applications.find(x=>x.id===req.params.id);if(!a)return res.status(404).json({error:'Nicht gefunden'});const allowed=['Eingegangen','In Prüfung','Nachreichung erforderlich','Termin erforderlich','Entscheidung getroffen','Abgeschlossen'];if(req.body.status&&!allowed.includes(req.body.status))return res.status(400).json({error:'Ungültiger Status'});if(req.body.status&&req.body.status!==a.status){a.status=req.body.status;a.timeline.push({status:a.status,date:new Date().toISOString(),note:req.body.note||''})}if(req.body.note)a.adminNote=req.body.note;a.updatedAt=new Date().toISOString();write(d);res.json(a)});
app.get('/api/admin/users',admin,(req,res)=>res.json(read().users.map(u=>({id:u.id,name:u.firstName+' '+u.lastName,email:u.email,createdAt:u.createdAt}))));
app.post('/api/messages',auth,(req,res)=>{const {applicationId,text}=req.body;if(!text)return res.status(400).json({error:'Nachricht fehlt'});const d=read();d.messages.push({id:'M-'+Date.now(),applicationId,userId:req.user.id,from:req.user.role==='admin'?'admin':'user',text,createdAt:new Date().toISOString()});write(d);res.json({ok:true})});
app.get('/api/messages/:applicationId',auth,(req,res)=>{const d=read();const a=d.applications.find(x=>x.id===req.params.applicationId);if(!a|| (req.user.role!=='admin'&&a.userId!==req.user.id))return res.status(404).json({error:'Nicht gefunden'});res.json(d.messages.filter(m=>m.applicationId===a.id))});
app.get('/api/health',(req,res)=>res.json({ok:true,service:'Independent Visa Portal'}));
app.get('*',(req,res)=>res.sendFile(path.join(ROOT,'public','index.html')));
app.listen(PORT,'0.0.0.0',()=>console.log(`Portal running on port ${PORT}`));
